rule_files:
  - alert_rules.yaml
# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: api_gateway
    scrape_interval: 10s
    static_configs:
      - targets: ['api_gateway:15000']